apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile
  labels:
    name: profile
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: profile
      app.kubernetes.io/instance: profile
  template:
    metadata:
      labels:
        app.kubernetes.io/name: profile
        app.kubernetes.io/instance: profile
    spec:
      containers:
        - name: profile
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP