apiVersion: v1
kind: Service
metadata:
  name: profile
  labels:
    app.kubernetes.io/name: profile
    app.kubernetes.io/instance: profile
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: profile
    app.kubernetes.io/instance: profile
