version: 2.1
jobs:
  set-up-workspace:
    docker:
      - image: cimg/base:stable  
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .

  build-docker-image:
    docker:
      - image: cimg/base:stable  
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            cd /tmp/workspace/profile
            echo "${G_CLOUD_SERVICE_KEY}" > serviceaccount.json
            docker login -u _json_key --password-stdin https://gcr.io < serviceaccount.json
            docker build -t us.gcr.io/altschool-371614/profile:$CIRCLE_SHA1 .
            docker push us.gcr.io/altschool-371614/profile:$CIRCLE_SHA1

workflows:
  deploy:
    jobs:
      - set-up-workspace
      - build-docker-image:
          requires:
            - set-up-workspace