version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.15.1
jobs:
  build-and-push:
    executor: gcp-gcr/default
    steps:
      - checkout
      - gcp-gcr/gcr-auth:
          gcloud-service-key: G_CLOUD_SERVICE_KEY
          google-project-id: altschool-371614
      - gcp-gcr/build-image:
          google-project-id: altschool-371614
          image: profile
          no_output_timeout: 20m
          registry-url: us.gcr.io
      - gcp-gcr/push-image:
          gcloud-service-key: G_CLOUD_SERVICE_KEY
          google-project-id: altschool-371614
          image: profile
          registry-url: us.gcr.io
workflows:
  commit:
    jobs:
      - build-and-push
