ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
  path: /?(.*)
  hosts:
    - grafana.k317.live

  grafana.ini:
    server:
      root_url: http://localhost:3000/grafana # this host can be localhost